name: PR Checks

on:
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: |
          uv sync --dev

      - name: Run unit tests
        run: |
          uv run pytest tests/unit -v --tb=short

      - name: Run integration tests
        run: |
          uv run pytest tests/integration -v --tb=short

      - name: Check code style with ruff
        run: |
          uv run ruff check . --diff
          uv run ruff format . --check --diff
        continue-on-error: true

      - name: Type checking with mypy
        run: |
          uv run mypy app tests --no-error-summary
        continue-on-error: true

      - name: Spell check with codespell
        run: |
          uv run codespell
        continue-on-error: true

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        continue-on-error: true

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: syncflow-api:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
